language: python
python:
  - "3.7"
before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && chmod 577 Miniconda3-latest-Linux-x86_64.sh
  - ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda3
# command to install dependencies
install:
  - pip install -r requirements.txt
  - conda install -c bioconda jellyfish
# command to run tests
script:
  - pytest