language: python
python:
  - "3.7"
before_install:
  - wget https://github.com/gmarcais/Jellyfish/releases/download/v2.3.0/jellyfish-2.3.0.tar.gz && tar -zxvf jellyfish-2.3.0.tar.gz && cd jellyfish-2.3.0
  - ./configure --prefix=$HOME
  - make -j 4
  - make install
  - cd ../
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest